name: ring_flutter_sdk
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  binarize: ^1.5.0
  bluetooth_low_energy: ^5.0.6
  collection: ^1.18.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.10
  meta: ^1.10.0
  permission_handler: ^11.3.0
  pretty_print_json: ^1.0.1
  signals_flutter: ^4.4.0
  stack_trace: ^1.11.1
  universal_ble: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
